#!/usr/bin/env python3
main_mongodb_uri = "mongodb://CNET:CnET_mongo_1_!@172.31.26.143:27017/ehubdata?authSource=ehubdata"
#main_mongodb_uri = "mongodb://127.0.0.1:27017"
main_mongodb = "ehubdata"
local_mongodb_uri = "mongodb://127.0.0.1:27017"
local_mongodb = "analytics"
#main_config_db="127.0.0.1"
#config_db_user="mysqluser"
#config_db_password="hemligt"
main_config_db="172.31.26.143"
config_db_user="CNET"
config_db_password="CnET_MYSQL_1?_!"

EHUBDATAS="ehubdatas"
CONFIG_DB="ferroamps"
BASE_LOAD_DAILY="base_load_daily"
POWERANALYSISDAILY_JOBS="poweranalysisday_jobs"
POWERANALYSISDAILY_RESULTS="poweranalysisday_results"
ENERGY_COUNTER="energydata"
POWERANALYIS_DAILY_JOBS_RESULTS="poweranalysisday_jobs_results"
